### ISSUE TITLE
Update My Server?

### ISSUE THREAD

**Issue by admobwebmaster** [senkron24/XtreamUI#2]
Friend your work is excellent!
Thank you very much for continuing your work!
I'm using the Xtream UI R22B version, how can I update without losing my channel registration on the panel and all the data already installed on the friend server?

I will be very grateful for your help.

**Comment by senkron24** [comment]
thx mate
you can direckt update you not lose anything ..
kind regarts

**Comment by admobwebmaster** [comment]
How so friend!

**Comment by senkron24** [comment]
first this comand

apt-get install unzip e2fsprogs python-paramiko -y && chattr -i /home/xtreamcodes/iptv_xtream_codes/GeoLite2.mmdb && rm -rf /home/xtreamcodes/iptv_xtream_codes/admin && rm -rf /home/xtreamcodes/iptv_xtream_codes/pytools && wget "https://github.com/senkron24/XtreamUI/archive/master.zip" -O /tmp/master.zip -o /dev/null && unzip /tmp/master.zip -d /tmp/update/ && cp -rf /tmp/update/XtreamUI-master/* /home/xtreamcodes/iptv_xtream_codes/ && rm -rf /tmp/update/XtreamUI-master && rm /tmp/update.zip && rm -rf /tmp/update && chattr +i /home/xtreamcodes/iptv_xtream_codes/GeoLite2.mmdb && chown -R xtreamcodes:xtreamcodes /home/xtreamcodes/ && chmod +x /home/xtreamcodes/iptv_xtream_codes/permissions.sh && /home/xtreamcodes/iptv_xtream_codes/permissions.sh && /home/xtreamcodes/iptv_xtream_codes/start_services.sh


than this comand 

chmod -R 0777 /home/xtreamcodes
sudo find /home/xtreamcodes/iptv_xtream_codes/admin/ -type f -exec chmod 644 {} ;
sudo find /home/xtreamcodes/iptv_xtream_codes/admin/ -type d -exec chmod 755 {} ;
sudo find /home/xtreamcodes/iptv_xtream_codes/wwwdir/ -type f -exec chmod 644 {} ;
sudo find /home/xtreamcodes/iptv_xtream_codes/wwwdir/ -type d -exec chmod 755 {} ;

it will work without any problem ..

**Comment by admobwebmaster** [comment]
Friend I am grateful for your help, I successfully updated. thank you very much.
