### ISSUE TITLE
Delete duplicate Movies and Episodes

### ISSUE THREAD

**Issue by jennyrach** [senkron24/XtreamUI#5]
I cant make it work directly in movies.php, the most I could do was making a new php file, that I call, run this and return to movies.php

Movies
delete t1 FROM streams t1 INNER JOIN streams t2 WHERE t1.id < t2.id AND t1.stream_display_name = t2.stream_display_name AND t1.type=2 AND t2.type=2

Episodes
delete t1 FROM streams t1 INNER JOIN streams t2 WHERE t1.id < t2.id AND t1.stream_display_name = t2.stream_display_name AND t1.type=2 AND t2.type=5

**Comment by senkron24** [comment]
thanks you my freand i will not add this to orginal 22F bud if sambudy need it can intregread code in him self..
again thanks for you share this with us ..

kind regarts
